extends: base.yaml
models:
  woe_lr:
    enabled: false
  random_forest:
    enabled: false
  xgboost:
    enabled: false
  lr:
    enabled: true
    params:
      C: 0.1
      solver: liblinear
      max_iter: 1000
      class_weight: balanced
